"""
Generate a Markdown summary report from Dependabot alerts.

This script reads the raw Dependabot alerts JSON (generated by alerts.py),
sorts the alerts by severity, extracts key vulnerability details, and
produces a Markdown table containing information such as:

- Manifest path
- Dependency name
- Ecosystem
- Dependency scope and relationship
- CVE ID and GHSA ID
- Vulnerability summary
- Severity
- CVSS score
- Vulnerable version range
- First patched version
- Alert URL

The generated report is written to the output Markdown file and is intended
to be appended to the GitHub Actions Job Summary while also being uploaded
as a workflow artifact.

Usage:
    python scan_summary.py <input_json> <output_markdown>
"""

import json, sys

src, dst = sys.argv[1], sys.argv[2]
alerts = json.load(open(src))

SEV_EMOJI = {
    "critical": "Critical",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
}
SEV_RANK = {"critical": 0, "high": 1, "medium": 2, "low": 3}

HEADERS = [
    "Manifest Path", "Dependency", "Ecosystem",
    "CVE ID", "GHSA ID", "Summary", "Severity",
    "CVSS Score", "Vulnerable Range", "First Patched Version", "Alert Link",
]

def clean(value):
    text = str(value) if value is not None else "N/A"
    return text.replace("|", "\\|").replace("\n", " ").strip() or "N/A"

def cvss_score(advisory):
    severities = advisory.get("cvss_severities") or {}
    v4_score = (severities.get("cvss_v4") or {}).get("score")
    if v4_score:
        return f"{v4_score:.1f} (v4)"

    v3_score = (severities.get("cvss_v3") or {}).get("score")
    if v3_score is not None:
        return f"{v3_score:.1f} (v3)"

    legacy_score = (advisory.get("cvss") or {}).get("score")
    if legacy_score is not None:
        return f"{legacy_score:.1f} (v3)"

    return "N/A"

def row_for(alert):
    dependency = alert.get("dependency") or {}
    package = dependency.get("package") or {}
    advisory = alert.get("security_advisory") or {}
    vulnerability = alert.get("security_vulnerability") or {}
    first_patched = (vulnerability.get("first_patched_version") or {}).get("identifier")

    return [
        dependency.get("manifest_path"),
        package.get("name"),
        package.get("ecosystem"),
        advisory.get("cve_id"),
        advisory.get("ghsa_id"),
        advisory.get("summary"),
        SEV_EMOJI.get((vulnerability.get("severity") or "").lower(), vulnerability.get("severity", "Unknown")),
        cvss_score(advisory),
        vulnerability.get("vulnerable_version_range"),
        first_patched,
        f"[Link]({alert.get('html_url')})",
    ]

lines = [
    "## 🔍 Scan Agent — Dependabot Alert Report",
    "",
    f"**Total open alerts found:** {len(alerts)}",
    "",
]

if not alerts:
    lines.append("_No open Dependabot alerts were found for this repository._")
else:
    lines.append("| " + " | ".join(HEADERS) + " |")
    lines.append("|" + "---|" * len(HEADERS))

    alerts_sorted = sorted(
        alerts,
        key=lambda a: SEV_RANK.get(((a.get("security_vulnerability") or {}).get("severity", "")).lower(), 4),
    )
    for alert in alerts_sorted:
        cells = [clean(v) for v in row_for(alert)]
        lines.append("| " + " | ".join(cells) + " |")

content = "\n".join(lines) + "\n"
open(dst, "w").write(content)
print(content)
